### ISSUE TITLE
Sample code for using TrueTypeSharp in Monogame

### ISSUE THREAD

**Issue by mfoda** [KonajuGames/TrueTypeSharp#2]
Hi,

I've bee scouring the Monogame forums looking for a solution for dynamic font rendering and found some of your posts:

http://community.monogame.net/t/loading-an-embed-spritefont/927/9
http://community.monogame.net/t/handling-dynamic-text-rendering/8393/2

I hope it's not too much to ask, but could you please explain how to do that with a short code sample? 

Thanks!

**Comment by KonajuGames** [comment]
I had a sample that used TrueTypeSharp in the MonoGame content pipeline instead of FreeType.  You can find it [here](https://github.com/KonajuGames/MonoGame/blob/truetypesharp/MonoGame.Framework.Content.Pipeline/Graphics/Font/SharpFontImporter.cs).

**Comment by mfoda** [comment]
Thanks. Would I need to copy this file to my project to use it, since it's an internal class.

Also, would it be possible to do it without `System.Drawing` since that is not supported on mobile?

**Comment by mfoda** [comment]
Actually, i'm a little confused by this:

`You could use a library such as TrueTypeSharp11 that loads a TTF file and generates a greyscale bitmap from supplied text.`

I thought that TrueTypeSharp would be able to generate the bitmap, not `System.Drawing`. Am  I misunderstanding?

**Comment by KonajuGames** [comment]
The use of `System.Drawing.Bitmap` was just an intermediary the content pipeline used at that time.  In more recent content pipeline code, `Bitmap` has been removed and replaced with `TextureContent`.  TrueTypeSharp returns a byte array containing values from 0 for black to 255 for white per pixel.  If you were wanting to use TrueTypeSharp at runtime, you would take this byte array and use `Texture2D.SetData()` on a `Texture2D` with `SurfaceFormat.Alpha8` to match the data that TrueTypeSharp returns.  Alternatively, convert each entry in the byte array to `Color` by using `new Color(value, value, value)` where `value` is the entry from the byte array.

I hope that makes sense.  And I think I gave you the wrong link before.  This is the [importer](https://github.com/KonajuGames/MonoGame/blob/truetypesharp/MonoGame.Framework.Content.Pipeline/Graphics/Font/TrueTypeSharpImporter.cs) that I wrote that used TrueTypeSharp.

**Comment by KonajuGames** [comment]
None of the code I linked to is anything that you could simply copy into your game.  You would have to write it yourself, using the code I linked to as a sample of how to use the TrueTypeSharp APIs.

**Comment by mfoda** [comment]
Ah, I see. I think I understand now. I'll give it a try and post my code here if it works then.

Really appreciate your help!

**Comment by mfoda** [comment]
It's almost working!

```csharp
var text = "你好";

var assembly = typeof(BPEditor).GetTypeInfo().Assembly;
var stream = assembly.GetManifestResourceStream("BPEditor.Content.Fonts.wts11.ttf");

var font = new TrueTypeFont(stream);

// Convert points to pixels as pointSize * 96 / 72
float pixelHeight = 48 * 96.0f / 72.0f;
float scale = font.GetScaleForMappingEmToPixels(pixelHeight);

foreach (var ch in text)
{
	int width, height, xOffset, yOffset;
	int index = font.FindGlyphIndex(ch);
	byte[] data = font.GetGlyphBitmap(index, scale, scale, out width, out height, out xOffset, out yOffset);

	var texture = new Texture2D(Core.graphicsDevice, width, height, mipmap: false, format: SurfaceFormat.Alpha8);
	texture.SetData(data);

	var fontSprite = new Sprite(texture);
        .. // use fontSprite
}
```

<img width="372" alt="screen shot 2017-02-16 at 23 35 21" src="https://cloud.githubusercontent.com/assets/23182653/23027874/a4f6c95e-f4a0-11e6-882a-0b183c1c64c0.png">


Just need to figure out how to get the text without the black part and an efficient way to render full sentences. Will update the code when I do.

Thanks so much @KonajuGames !

**Comment by KonajuGames** [comment]
Good to see the results so soon.  You would definitely want to cache the results so you don't keep rasterizing the same glyphs each frame.

**Comment by mfoda** [comment]
Hmm. Do you think it would be a good idea to collect all the bitmap data from the full text and render it into a single texture? I'm trying to do that but I think I need to do more than just concatenating all the byte arrays into single big byte array.

**Comment by mfoda** [comment]
@KonajuGames I still can't figure out how to remove the black background around the text. I tried to use the second method you mentioned, converting each byte array into a Color instead of using `SurfaceFormat.Alpha8` on a `Texture2D`, but I'm not sure what kind of data structure I should put these colors in and how to convert that into a final image, since there is no `Bitmap` class in Xamarin.

Any help would be much appreciated.

**Comment by mfoda** [comment]
Ok, I figured it out following @KonajuGames instructions. Here it is for anyone who might need it:

```csharp
var assembly = typeof(MyApp).GetTypeInfo().Assembly;
var stream = assembly.GetManifestResourceStream("MyApp.Content.Fonts.wts11.ttf");

var font = new TrueTypeFont(stream);

// Convert points to pixels as pointSize * 96 / 72
float pixelHeight = 48 * 96.0f / 72.0f;
float scale = font.GetScaleForMappingEmToPixels(pixelHeight);

foreach (var ch in text)
{
    int width, height, xOffset, yOffset;
    int index         = font.FindGlyphIndex(ch);
    byte[] data       = font.GetGlyphBitmap(index, scale, scale, out width, out height, out xOffset, out yOffset);
    Color[] colorData = new Color[width * height];
    var texture       = new Texture2D(Core.graphicsDevice, width, height);

    for (int i = 0; i < colorData.Length; i++)
        colorData[i] = new Color(data[i], data[i], data[i], data[i]);
				
    texture.SetData(colorData);
}				
```
